#pragma once
// Precompailed headers
#include <condition_variable>
#include <initializer_list>
#include <xmmintrin.h>
#include <functional>
#include <filesystem>
#include <exception>
#include <iostream>
#include <fstream>
#include <variant>
#include <sstream>
#include <vector>
#include <limits>
#include <string>
#include <future>
#include <thread>
#include <memory>
#include <regex>
#include <queue>
#include <array>
#include <map>
